services:
  - type: web
    name: tds-virtual-ta
    runtime: python
    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        value: eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjIyZjIwMDE3MjVAZHMuc3R1ZHkuaWl0bS5hYy5pbiJ9.9P4lOHN807o41A6gmMM2BNfrXmbwFMw1heiW-8J-Kng
